var loreIpsun='Lorem ipsum dolor sit amet, tristique justo odio suspendisse nisl, a sapien tellus libero. Ut wisi ultricies purus, non orci pede at, quis donec at dolor nulla. Suscipit viverra et ultricies, enim aliquet odio accumsan sem, vestibulum vestibulum tortor dolor pulvinar, morbi vitae ridiculus auctor. Vel posuere felis mattis blandit, wisi egestas aliquam justo. In eu amet id, pharetra non ante quam, in quam vel egestas. Adipiscing et a augue, morbi orci nulla in, nunc vitae metus eu dolor. Pulvinar maecenas sit sit etiam, hendrerit nulla feugiat dignissim. Est gravida nibh nec pellentesque, proin vitae sapien neque sapien. Vitae est pellentesque ridiculus mauris, posuere eu mauris dictum, suscipit mi sit elit rhoncus, curae libero in semper.\
\n\nProin nulla volutpat quis vitae, maecenas ultricies luctus lacus pretium. Ultricies iaculis sapien ante, magna quisque ultrices mauris. Ante magna molestie leo mi, nulla lobortis magnis lacus, id a fringilla sed dui. Mattis interdum porttitor ac nunc, orci etiam pellentesque sem lacus, a facilisis sed lacus, at purus aliquam id quis. Posuere rutrum eum elit, ac quam quisque magna gravida, dignissim sociis praesent lorem, tempus wisi etiam turpis. Imperdiet suspendisse turpis mollis eget, lectus nam voluptatibus nunc quis, non turpis ante ut urna. Velit semper lectus commodo metus, eget fermentum ac tortor orci, nullam etiam suspendisse adipiscing, mauris diam velit nec velit. Wisi aliquam sodales suspendisse, non vivamus velit nonummy. Arcu massa leo vestibulum, justo suscipit sollicitudin placerat.\
\n\nTincidunt dolores interdum phasellus, nullam laoreet pharetra ultricies. Venenatis magna vitae ipsum nulla, volutpat sodales nibh et. Suspendisse in viverra fusce at, phasellus elit vehicula leo, nullam nullam euismod feugiat, ipsum fermentum lectus enim nulla. Porttitor ipsa diam ante, morbi risus quis vestibulum sit, molestie fusce odio maecenas. Eleifend luctus accumsan amet augue, eget massa justo est. Adipiscing sed habitant risus mauris, justo tempor diam sit, penatibus ut justo curabitur fermentum, elementum interdum etiam diam urna. Lectus erat nisl litora, dolor amet nec ultrices erat, dui id dolor amet neque. Ipsum aptent sagittis aliquam, dignissim nulla pharetra quisque, nibh lectus malesuada quidem elit, purus urna eu sed lacus. \
\n\n';//Mi feugiat vitae turpis, libero iaculis mauris sollicitudin est, turpis praesent nisl neque. Justo enim ultricies vestibulum eget, aliquam ad aliquam rhoncus. Proin vestibulum nam orci, justo vivamus ligula odio viverra, egestas amet dolor viverra. Libero eros et nulla, mauris lorem voluptatem dapibus vitae, ipsum tempor porttitor diam velit, potenti vestibulum erat nec diam. Wisi dignissim convallis fusce, venenatis sit amet natoque. Eu vehicula etiam augue non, in eu elit donec facilisis, adipiscing wisi iaculis lacus sapien. Vestibulum vel sollicitudin ut, proin phasellus nulla eu, cras montes diam velit vitae, in nibh ultricies egestas luctus. Rem primis lobortis nibh magna, sed maecenas dui vulputate felis, hymenaeos diam lectus adipiscing mi.'

var pangram = 'The quick brown fox jumps over the lazy dog \
\n\nEl veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja. 1234567890 \
\n\nأبجد هوَّز حُطّي كلَمُن سَعْفَص قُرِشَت ثَخَدٌ ضَظَغ \
\n\nVictor jagt zwölf Boxkämpfer quer über den großen Sylter Deich';

var today = new Date();
var examples = 'Currency: $10, $10.99, $10.3333, 10.99$, 10.99£, 10.99ƒ, 10.99¥, 10,99€ \
\n\nIP address: 127.0.0.1, 255.255.255.255, 192.168.1.255, 192.168.1.1, 192.0.0.0, 192.168.2.1, 256.1.1.1 192.168.20\
\n\nDates: '+today.getFullYear()+'/'+(today.getMonth()+1)+'/'+today.getDate()+', 2012/07/27, 2012-07-27, 2012-30-30, 31045/07/27, 27/07/2012, 20/01/2012 '

var text=[examples,pangram,loreIpsun,''];